# This is a example deployment workflow for deploying you changes with helm. In this workflow we assume pre configured
# github secrets for your kubernetes cluster id, your kubernetes user id, your kubernetes access token and all secret
# values used for deployment.
name: Deployment Online Beratung Develop example

on:
  push:
    branches:
      - develop

jobs:
  develop:
    name: Deployment Workflow example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: true
          token: ${{ secrets.GH_PACKAGE_RELEASE_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: Helm upgrade
        if: contains(steps.changed-files.outputs.modified_files, 'values.yaml')
        uses: ./deployment
        with:
          ENVIRONMENT: develop
          GSCLOUD_CLUSTERID: ${{ secrets.GSCLOUD_CLUSTERID }}
          GSCLOUD_USERID: ${{ secrets.GSCLOUD_USERID }}
          GSCLOUD_TOKEN: ${{ secrets.GSCLOUD_TOKEN }}
          VALUES_SECRET_YAML: ${{ secrets.VALUES_SECRET_YAML }}
